### ISSUE TITLE
Unable to start the game

### ISSUE THREAD

**Issue by gocreating** [jonfranco224/not-my-cows#12]
I pressed `Enter` and nothing happened

**Comment by sol8712** [comment]
I get the same issue using Chromium browser.

Works great with Firefox, very fun game, send in more rocks over time please, it is satisfying to break a bunch at once.

**Comment by jonfranco224** [comment]
@gocreating - What browser and OS were you using?

@sol8712 @gocreating - Would you all be so kind as to try again here https://deploy-preview-13--notmycows.netlify.app/ to see if it's fixed in Chrome? I've modified the key listeners to use `e.code` instead of `e.key`. If it still doesn't work, can you record what you see here https://w3c.github.io/uievents/tools/key-event-viewer.html when you WASD, Arrows, Spacebar, and Enter?

I'm thinking if the keyboard is not the issue, it might be the simulation. Thanks in advance for the help!

**Comment by gocreating** [comment]
@jonfranco224 The fix works! Thanks!
